version: '2'
services:
  db:
    container_name: blog_db
    image: postgres
    ports:
      - "5432:5432"
  session:
    container_name: blog_session
    image: redis
    ports:
      - "6379:6379"
  geoip:
    container_name: blog_geoip
    image: fiorix/freegeoip
    ports:
      - "8080:8080"
  web:
    container_name: blog_app
    build: .
    command: bash -c "sleep 5 && bundle exec rake db:setup && SECRET_KEY_BASE=`rake secret` bundle exec unicorn -c config/unicorn.rb"
    volumes:
      - .:/blog
    ports:
      - "3000:3000"
    env_file:
      - config/deploy/production.env
    depends_on:
      - db
      - session
      - geoip
