version: '2'
services:
  db:
    container_name: blog_db
    image: postgres
    ports:
      - "5432:5432"
  session:
    container_name: blog_session
    image: redis
    ports:
      - "6379:6379"
  geoip:
    container_name: blog_geoip
    image: fiorix/freegeoip
    ports:
      - "8080:8080"
  web:
    container_name: blog_app
    build: .
    command: bash -c "SECRET_KEY_BASE=`rake secret` bundle exec rails s -p 3000 -b '0.0.0.0' -e production"
    volumes:
      - .:/blog
    ports:
      - "3000:3000"
    depends_on:
      - db
      - session
      - geoip
